//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCTimeSheet_UTIL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCTimeSheet_UTIL.Resource.ResourceMessage", typeof(ResourceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Project is Already Assigned With this Employee.
        /// </summary>
        public static string Alreadyexist {
            get {
                return ResourceManager.GetString("Alreadyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve/Reject Comment is Required.
        /// </summary>
        public static string ApproveRejComm {
            get {
                return ResourceManager.GetString("ApproveRejComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Count is Exceeded.
        /// </summary>
        public static string DayscountExceed {
            get {
                return ResourceManager.GetString("DayscountExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Assignment  EndDate of Employee is greaterthan the Project End Date.
        /// </summary>
        public static string Enddateexceed {
            get {
                return ResourceManager.GetString("Enddateexceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email.
        /// </summary>
        public static string IncorrectUsername {
            get {
                return ResourceManager.GetString("IncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Valid Date.
        /// </summary>
        public static string InvolveMonthInValid {
            get {
                return ResourceManager.GetString("InvolveMonthInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for this project already exist.
        /// </summary>
        public static string InvolveMonthValid {
            get {
                return ResourceManager.GetString("InvolveMonthValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involve Percentage is Required.
        /// </summary>
        public static string InvolvePercent {
            get {
                return ResourceManager.GetString("InvolvePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement Percentage Required.
        /// </summary>
        public static string InvolvePerEmpty {
            get {
                return ResourceManager.GetString("InvolvePerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Involvment Percentage is Exceeded (More than 100 %).
        /// </summary>
        public static string Invpercexceed {
            get {
                return ResourceManager.GetString("Invpercexceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Approved Successfully.
        /// </summary>
        public static string NewEntryApprove {
            get {
                return ResourceManager.GetString("NewEntryApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved as draft.
        /// </summary>
        public static string NewEntryDraft {
            get {
                return ResourceManager.GetString("NewEntryDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is Rejected.
        /// </summary>
        public static string NewEntryRejected {
            get {
                return ResourceManager.GetString("NewEntryRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data submitted successfully. Waiting for approval.
        /// </summary>
        public static string NewEntrySubmit {
            get {
                return ResourceManager.GetString("NewEntrySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is approved successfully .
        /// </summary>
        public static string NewEntrySubmitOnBehalf {
            get {
                return ResourceManager.GetString("NewEntrySubmitOnBehalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully.
        /// </summary>
        public static string NewEntryUpdate {
            get {
                return ResourceManager.GetString("NewEntryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details Added Successfully.
        /// </summary>
        public static string NewProjectAdd {
            get {
                return ResourceManager.GetString("NewProjectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details Successfully Assigned.
        /// </summary>
        public static string NewProjectAddEmp {
            get {
                return ResourceManager.GetString("NewProjectAddEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated Successfully.
        /// </summary>
        public static string NewProjectAddEmpUpdate {
            get {
                return ResourceManager.GetString("NewProjectAddEmpUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details Deleted Successfully.
        /// </summary>
        public static string NewProjectDelete {
            get {
                return ResourceManager.GetString("NewProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details Updated Successfully.
        /// </summary>
        public static string NewProjectUpdate {
            get {
                return ResourceManager.GetString("NewProjectUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role exists.
        /// </summary>
        public static string NoRole {
            get {
                return ResourceManager.GetString("NoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Configured Successfully.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdate is greater than Enddate .
        /// </summary>
        public static string Startdate {
            get {
                return ResourceManager.GetString("Startdate", resourceCulture);
            }
        }
    }
}
