//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCTimeSheet_UTIL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCTimeSheet_UTIL.Resource.ResourceDisplay", typeof(ResourceDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is PM.
        /// </summary>
        public static string CheckRole {
            get {
                return ResourceManager.GetString("CheckRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string CostCentre {
            get {
                return ResourceManager.GetString("CostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmpId {
            get {
                return ResourceManager.GetString("EmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string EmpRemarks {
            get {
                return ResourceManager.GetString("EmpRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement Days.
        /// </summary>
        public static string InvolveDaysCount {
            get {
                return ResourceManager.GetString("InvolveDaysCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement Edit Days.
        /// </summary>
        public static string InvolveDaysEditCount {
            get {
                return ResourceManager.GetString("InvolveDaysEditCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement Month.
        /// </summary>
        public static string InvolveMonth {
            get {
                return ResourceManager.GetString("InvolveMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement Percentage.
        /// </summary>
        public static string InvolvePercent {
            get {
                return ResourceManager.GetString("InvolvePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involvement Percentage.
        /// </summary>
        public static string InvPercentage {
            get {
                return ResourceManager.GetString("InvPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PageID {
            get {
                return ResourceManager.GetString("PageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        public static string PersonalID {
            get {
                return ResourceManager.GetString("PersonalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string ProjectDesc {
            get {
                return ResourceManager.GetString("ProjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant.
        /// </summary>
        public static string ProjectGrant {
            get {
                return ResourceManager.GetString("ProjectGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quarter.
        /// </summary>
        public static string QID {
            get {
                return ResourceManager.GetString("QID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportID {
            get {
                return ResourceManager.GetString("ReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of Research.
        /// </summary>
        public static string ResearchArea {
            get {
                return ResourceManager.GetString("ResearchArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days For Enabling Quarter Updation.
        /// </summary>
        public static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Type.
        /// </summary>
        public static string TypeofResearch {
            get {
                return ResourceManager.GetString("TypeofResearch", resourceCulture);
            }
        }
    }
}
